// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHakETDDZ3tMZ-Fy9hwGPclDV0Ue7yfVQ',
    appId: '1:849218746796:android:517ea51813d4bf42e12209',
    messagingSenderId: '849218746796',
    projectId: 'ai-chat-7e579',
    storageBucket: 'ai-chat-7e579.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Fhs-YWGd80SsXiAJbl91nLNgIb90GHo',
    appId: '1:849218746796:ios:0b133ba5d6d79fe3e12209',
    messagingSenderId: '849218746796',
    projectId: 'ai-chat-7e579',
    storageBucket: 'ai-chat-7e579.firebasestorage.app',
    iosBundleId: 'com.example.aiChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_Fhs-YWGd80SsXiAJbl91nLNgIb90GHo',
    appId: '1:849218746796:ios:0b133ba5d6d79fe3e12209',
    messagingSenderId: '849218746796',
    projectId: 'ai-chat-7e579',
    storageBucket: 'ai-chat-7e579.firebasestorage.app',
    iosBundleId: 'com.example.aiChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtZG_J0fHgKg7e9fmwUYrJEKZzLCFivAI',
    appId: '1:849218746796:web:c2e3f8ea410d0987e12209',
    messagingSenderId: '849218746796',
    projectId: 'ai-chat-7e579',
    authDomain: 'ai-chat-7e579.firebaseapp.com',
    storageBucket: 'ai-chat-7e579.firebasestorage.app',
    measurementId: 'G-LGLZGFD7GQ',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtZG_J0fHgKg7e9fmwUYrJEKZzLCFivAI',
    appId: '1:849218746796:web:c2e3f8ea410d0987e12209',
    messagingSenderId: '849218746796',
    projectId: 'ai-chat-7e579',
    authDomain: 'ai-chat-7e579.firebaseapp.com',
    storageBucket: 'ai-chat-7e579.firebasestorage.app',
    measurementId: 'G-LGLZGFD7GQ',
  );

}